### ISSUE TITLE
Monokai unreadable

### ISSUE THREAD

**Issue by Alexey-T** [THWLF/CudaText-registry#1]
too dark on Pascal file.
gutter color not like text BG

![monok](https://cloud.githubusercontent.com/assets/4154978/21583990/4b1b4504-d0b0-11e6-883c-2104d9e977c5.png)

**Comment by Alexey-T** [comment]
Test pls on this:
https://github.com/Alexey-T/lexer_tests/tree/master/test_CudaText_color_themes

**Comment by THWLF** [comment]
I have tested it with new Cudatext instalation on linux i have no issues
![monokai](https://cloud.githubusercontent.com/assets/11279117/21589402/9449a4aa-d0f1-11e6-8045-ac433218acbf.png)

**Comment by Alexey-T** [comment]
MAnokai - file1
MOnokai- file2
so Cud cannot find 2nd file by auto match

**Comment by THWLF** [comment]
ok, i have fixed it now

**Comment by Alexey-T** [comment]
Sublim Monokai has
- white html brackets
- green html attrs
- same gutter BG as text BG
- listbox (comand palette) other color

**Comment by THWLF** [comment]
ok i have make additional fixxes
